sudo: required
dist: trusty
language: node_js
node_js:
  - '6.9.2'
  #- '6.9.1'
  #- '6.9.0'
  #- '6.8.1'
  #- '6.8.0'
  #- '6.7.0'
  #- '6.6.0'
  #- '6.5.0'

branches:
  only:
  - testing

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install -g angular-cli
- npm install -g karma
- npm install
- ng build

after_success:
- bash ./travis-ci/deploy.sh
