export const PhotographyPortfolios = [
  {
    id: 1,
    title: 'Natural Landscape',
    imageUrl: '/assets/images/natural-landscape/EchoLake_10-2017.jpg',
    route: 'natural-landscape',
    children: [],
    items: [
      { id: 11, title: 'Angels Landing, May 2017', description: '', imageUrl: '/assets/images/natural-landscape/AngelsLanding_05-2017.jpg' },
      { id: 12, title: 'Cable Arch, May 2017', description: '', imageUrl: '/assets/images/natural-landscape/CableArch_05-2017.jpg' },
      { id: 13, title: 'Cairns On Mount Washington, August 2017', description: '', imageUrl: '/assets/images/natural-landscape/CairnsOnMountWashington_08-2017.jpg' },
      { id: 14, title: 'Devils Doorway, January 2017', description: '', imageUrl: '/assets/images/natural-landscape/DevilsDoorway_01-2017.jpg' },
      { id: 15, title: 'Dream Beach, November 2016', description: '', imageUrl: '/assets/images/natural-landscape/DreamBeach_11-2016.jpg' },
      { id: 16, title: 'Eagle Falls, June 2017', description: '', imageUrl: '/assets/images/natural-landscape/EagleFalls_06-2017.jpg' },
      { id: 17, title: 'Echo Lake, October 2017', description: '', imageUrl: '/assets/images/natural-landscape/EchoLake_10-2017.jpg' },
      { id: 18, title: 'Fall Foliage, October 2017', description: '', imageUrl: '/assets/images/natural-landscape/FallFoliage_10-2017.jpg' },
      { id: 19, title: 'Indian Rock, June 2017', description: '', imageUrl: '/assets/images/natural-landscape/IndianRock_06-2017.jpg' },
      { id: 110, title: 'Jenny Lake, June 2017', description: '', imageUrl: '/assets/images/natural-landscape/JennyLake_06-2017.jpg' },
      { id: 111, title: 'Just Hanging Around, February 2017', description: '', imageUrl: '/assets/images/natural-landscape/JustHangingAround_02-2017.jpg' },
      { id: 112, title: 'Maroon Bells, May 2017', description: '', imageUrl: '/assets/images/natural-landscape/MaroonBells_05-2017.jpg' },
      { id: 113, title: 'Monterey, May 2017', description: '', imageUrl: '/assets/images/natural-landscape/Monterey_05-2017.jpg' },
      { id: 114, title: 'Mount Washington Railroad, August 2017', description: '', imageUrl: '/assets/images/natural-landscape/MountWashingtonRailroad_08-2017.jpg' },
      { id: 115, title: 'Muir Woods, June 2017', description: '', imageUrl: '/assets/images/natural-landscape/MuirWoods_06-2017.jpg' },
      { id: 116, title: 'Pemigewasset Overlook, August 2017', description: '', imageUrl: '/assets/images/natural-landscape/PemigewassetOverlook_08-2017.jpg' },
      { id: 117, title: 'Pemigewasset Sunset, August 2017', description: '', imageUrl: '/assets/images/natural-landscape/PemigewassetSunset_08-2017.jpg' },
      { id: 118, title: 'Provincetown, October 2017', description: '', imageUrl: '/assets/images/natural-landscape/Provincetown_10-2017.jpg' },
      { id: 119, title: 'Sedona, May 2017', description: '', imageUrl: '/assets/images/natural-landscape/Sedona_05-2017.jpg' },
      { id: 120, title: 'Taggart Lake, June 2017', description: '', imageUrl: '/assets/images/natural-landscape/TaggartLake_06-2017.jpg' },
      { id: 121, title: 'Taroko National Park, October 2016', description: '', imageUrl: '/assets/images/natural-landscape/TarokoNationalPark_10-2016.jpg' },
      { id: 122, title: 'The Grand Tetons, June 2017', description: '', imageUrl: '/assets/images/natural-landscape/TheGrandTetons_06-2017.jpg' },
      { id: 123, title: 'Waning Gibbous, February 2017', description: '', imageUrl: '/assets/images/natural-landscape/WaningGibbous_02-2017.jpg' },
      { id: 124, title: 'White Horse Ledge, October 2017', description: '', imageUrl: '/assets/images/natural-landscape/WhiteHorseLedge_10-2017.jpg' },
    ]   
  } 
];