export const PhotographyPortfolios = [
  {
    id: 1,
    title: 'Natural Landscape',
    imageUrl: '/assets/images/natural-landscape/EchoLake_10-2017.jpg',
    placeholderImageUrl: '/assets/images/natural-landscape-placeholders/EchoLake_10-2017.jpg',
    route: 'natural-landscape',
    children: [],
    items: [
      { id: 11, title: 'Angels Landing, May 2017', description: '', imageUrl: '/assets/images/natural-landscape/AngelsLanding_05-2017.jpg', placeholderImageUrl: '/assets/images/natural-landscape-placeholders/AngelsLanding_05-2017.jpg' },
      { id: 12, title: 'Cable Arch, May 2017', description: '', imageUrl: '/assets/images/natural-landscape/CableArch_05-2017.jpg', placeholderImageUrl: '/assets/images/natural-landscape-placeholders/CableArch_05-2017.jpg' },
      { id: 13, title: 'Cairns On Mount Washington, August 2017', description: '', imageUrl: '/assets/images/natural-landscape/CairnsOnMountWashington_08-2017.jpg', placeholderImageUrl: '/assets/images/natural-landscape-placeholders/CairnsOnMountWashington_08-2017.jpg' },
      { id: 14, title: 'Devils Doorway, January 2017', description: '', imageUrl: '/assets/images/natural-landscape/DevilsDoorway_01-2017.jpg', placeholderImageUrl: '/assets/images/natural-landscape-placeholders/DevilsDoorway_01-2017.jpg' },
      { id: 15, title: 'Dream Beach, November 2016', description: '', imageUrl: '/assets/images/natural-landscape/DreamBeach_11-2016.jpg', placeholderImageUrl: '/assets/images/natural-landscape-placeholders/DreamBeach_11-2016.jpg' },
      { id: 16, title: 'Eagle Falls, June 2017', description: '', imageUrl: '/assets/images/natural-landscape/EagleFalls_06-2017.jpg', placeholderImageUrl: '/assets/images/natural-landscape-placeholders/EagleFalls_06-2017.jpg' },
      { id: 17, title: 'Echo Lake, October 2017', description: '', imageUrl: '/assets/images/natural-landscape/EchoLake_10-2017.jpg', placeholderImageUrl: '/assets/images/natural-landscape-placeholders/EchoLake_10-2017.jpg' },
      { id: 18, title: 'Fall Foliage, October 2017', description: '', imageUrl: '/assets/images/natural-landscape/FallFoliage_10-2017.jpg', placeholderImageUrl: '/assets/images/natural-landscape-placeholders/FallFoliage_10-2017.jpg' },
      { id: 19, title: 'Indian Rock, June 2017', description: '', imageUrl: '/assets/images/natural-landscape/IndianRock_06-2017.jpg', placeholderImageUrl: '/assets/images/natural-landscape-placeholders/IndianRock_06-2017.jpg' },
      { id: 110, title: 'Jenny Lake, June 2017', description: '', imageUrl: '/assets/images/natural-landscape/JennyLake_06-2017.jpg', placeholderImageUrl: '/assets/images/natural-landscape-placeholders/JennyLake_06-2017.jpg' },
      { id: 111, title: 'Just Hanging Around, February 2017', description: '', imageUrl: '/assets/images/natural-landscape/JustHangingAround_02-2017.jpg', placeholderImageUrl: '/assets/images/natural-landscape-placeholders/JustHangingAround_02-2017.jpg' },
      { id: 112, title: 'Maroon Bells, May 2017', description: '', imageUrl: '/assets/images/natural-landscape/MaroonBells_05-2017.jpg', placeholderImageUrl: '/assets/images/natural-landscape-placeholders/MaroonBells_05-2017.jpg' },
      { id: 113, title: 'Monterey, May 2017', description: '', imageUrl: '/assets/images/natural-landscape/Monterey_05-2017.jpg', placeholderImageUrl: '/assets/images/natural-landscape-placeholders/Monterey_05-2017.jpg' },
      { id: 114, title: 'Mount Washington Railroad, August 2017', description: '', imageUrl: '/assets/images/natural-landscape/MountWashingtonRailroad_08-2017.jpg', placeholderImageUrl: '/assets/images/natural-landscape-placeholders/MountWashingtonRailroad_08-2017.jpg' },
      { id: 115, title: 'Muir Woods, June 2017', description: '', imageUrl: '/assets/images/natural-landscape/MuirWoods_06-2017.jpg', placeholderImageUrl: '/assets/images/natural-landscape-placeholders/MuirWoods_06-2017.jpg' },
      { id: 116, title: 'Pemigewasset Overlook, August 2017', description: '', imageUrl: '/assets/images/natural-landscape/PemigewassetOverlook_08-2017.jpg', placeholderImageUrl: '/assets/images/natural-landscape-placeholders/PemigewassetOverlook_08-2017.jpg' },
      { id: 117, title: 'Pemigewasset Sunset, August 2017', description: '', imageUrl: '/assets/images/natural-landscape/PemigewassetSunset_08-2017.jpg', placeholderImageUrl: '/assets/images/natural-landscape-placeholders/PemigewassetSunset_08-2017.jpg' },
      { id: 118, title: 'Provincetown, October 2017', description: '', imageUrl: '/assets/images/natural-landscape/Provincetown_10-2017.jpg', placeholderImageUrl: '/assets/images/natural-landscape-placeholders/Provincetown_10-2017.jpg' },
      { id: 119, title: 'Sedona, May 2017', description: '', imageUrl: '/assets/images/natural-landscape/Sedona_05-2017.jpg', placeholderImageUrl: '/assets/images/natural-landscape-placeholders/Sedona_05-2017.jpg' },
      { id: 120, title: 'Taggart Lake, June 2017', description: '', imageUrl: '/assets/images/natural-landscape/TaggartLake_06-2017.jpg', placeholderImageUrl: '/assets/images/natural-landscape-placeholders/TaggartLake_06-2017.jpg' },
      { id: 121, title: 'Taroko National Park, October 2016', description: '', imageUrl: '/assets/images/natural-landscape/TarokoNationalPark_10-2016.jpg', placeholderImageUrl: '/assets/images/natural-landscape-placeholders/TarokoNationalPark_10-2016.jpg' },
      { id: 122, title: 'The Grand Tetons, June 2017', description: '', imageUrl: '/assets/images/natural-landscape/TheGrandTetons_06-2017.jpg', placeholderImageUrl: '/assets/images/natural-landscape-placeholders/TheGrandTetons_06-2017.jpg' },
      { id: 123, title: 'Waning Gibbous, February 2017', description: '', imageUrl: '/assets/images/natural-landscape/WaningGibbous_02-2017.jpg', placeholderImageUrl: '/assets/images/natural-landscape-placeholders/WaningGibbous_02-2017.jpg' },
      { id: 124, title: 'White Horse Ledge, October 2017', description: '', imageUrl: '/assets/images/natural-landscape/WhiteHorseLedge_10-2017.jpg', placeholderImageUrl: '/assets/images/natural-landscape-placeholders/WhiteHorseLedge_10-2017.jpg' },
    ]
  },
  {
    id: 2,
    title: 'Adventure',
    imageUrl: '/assets/images/adventure/IceAgeNationalScenicTrail_01-2017.jpg',
    placeholderImageUrl: '/assets/images/adventure-placeholders/IceAgeNationalScenicTrail_01-2017.jpg',
    route: 'adventure',
    children: [],
    items: [
      { id: 21, title: '17 Mile Drive, May 2017', description: '', imageUrl: '/assets/images/adventure/17MileDrive_05-2017.jpg', placeholderImageUrl: '/assets/images/adventure-placeholders/17MileDrive_05-2017.jpg' },
      { id: 22, title: 'Alpine Garden Trail, August 2017', description: '', imageUrl: '/assets/images/adventure/AlpineGardenTrail_08-2017.jpg', placeholderImageUrl: '/assets/images/adventure-placeholders/AlpineGardenTrail_08-2017.jpg' },
      { id: 23, title: 'Corona Arch, May 2017', description: '', imageUrl: '/assets/images/adventure/CoronaArch_05-2017.jpg', placeholderImageUrl: '/assets/images/adventure-placeholders/CoronaArch_05-2017.jpg' },
      { id: 24, title: 'Devils Lake East Bluff, January 2017', description: '', imageUrl: '/assets/images/adventure/DevilsLakeEastBluff_01-2017.jpg', placeholderImageUrl: '/assets/images/adventure-placeholders/DevilsLakeEastBluff_01-2017.jpg' },
      { id: 25, title: 'D L Bliss State Park, June 2017', description: '', imageUrl: '/assets/images/adventure/DLBlissStatePark_06-2017.jpg', placeholderImageUrl: '/assets/images/adventure-placeholders/DLBlissStatePark_06-2017.jpg' },
      { id: 26, title: 'Emerald Bay, June 2017', description: '', imageUrl: '/assets/images/adventure/EmeraldBay_06-2017.jpg', placeholderImageUrl: '/assets/images/adventure-placeholders/EmeraldBay_06-2017.jpg' },
      { id: 27, title: 'Ice Age National Scenic Trail, January 2017', description: '', imageUrl: '/assets/images/adventure/IceAgeNationalScenicTrail_01-2017.jpg', placeholderImageUrl: '/assets/images/adventure-placeholders/IceAgeNationalScenicTrail_01-2017.jpg' },
      { id: 28, title: 'Irwin Idaho, June 2017', description: '', imageUrl: '/assets/images/adventure/IrwinIdaho_06-2017.jpg', placeholderImageUrl: '/assets/images/adventure-placeholders/IrwinIdaho_06-2017.jpg' },
      { id: 29, title: 'Nelson Crag Trailhead, August 2017', description: '', imageUrl: '/assets/images/adventure/NelsonCragTrailhead_08-2017.jpg', placeholderImageUrl: '/assets/images/adventure-placeholders/NelsonCragTrailhead_08-2017.jpg' },
      { id: 210, title: 'Owl Rock, West Crack, Arches National Park, May 2017', description: '', imageUrl: '/assets/images/adventure/OwlRockWestCrack_05-2017.jpg', placeholderImageUrl: '/assets/images/adventure-placeholders/OwlRockWestCrack_05-2017.jpg' },
      { id: 211, title: 'Puerto Vallarta, Mexico, March 2017', description: '', imageUrl: '/assets/images/adventure/PuertoVallartaMexico_03-2017.jpg', placeholderImageUrl: '/assets/images/adventure-placeholders/PuertoVallartaMexico_03-2017.jpg' },
      { id: 212, title: 'Race Point Beach, October 2017', description: '', imageUrl: '/assets/images/adventure/RacePointBeach_10-2017.jpg', placeholderImageUrl: '/assets/images/adventure-placeholders/RacePointBeach_10-2017.jpg' }
    ]
  }
];
